M1Tests = executable('m1-tests', 'M1.cpp', dependencies : FeatherDependency)
test('m1', M1Tests)
M2Tests = executable('m2-tests', 'M2.cpp', dependencies : FeatherDependency)
test('m2', M2Tests)
M3Tests = executable('m3-tests', 'M3.cpp', dependencies : FeatherDependency)
test('m3', M3Tests)
EmbedTests = executable('embed-tests', 'Embed.cpp', dependencies : FeatherDependency)
test('embed', EmbedTests)
M4Tests = executable('m4-tests', 'M4.cpp', dependencies : FeatherDependency)
test('m4', M4Tests)
